# Generated by Django 5.0.3 on 2024-03-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('gp', models.CharField(max_length=100)),
                ('admitted', models.DateField(auto_now=True)),
                ('upload', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('FT', 'FULLTIME'), ('PT', 'PARTTIME'), ('SW', 'SANDWICH'), ('UN', 'UNKNOWN')], default='UN', max_length=2)),
            ],
            options={
                'ordering': ['-upload'],
                'indexes': [models.Index(fields=['upload'], name='students_st_upload_9880c2_idx')],
            },
        ),
    ]
