# Generated by Django 5.0.3 on 2024-03-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('nationality', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
                ('dob', models.CharField(max_length=225)),
                ('faculty', models.CharField(max_length=225)),
                ('qualifification', models.CharField(max_length=225)),
                ('department', models.CharField(max_length=225)),
                ('designation', models.CharField(max_length=225)),
                ('salary', models.CharField(max_length=225)),
                ('join_date', models.DateField(null=True)),
                ('photo', models.CharField(max_length=225)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('AS', 'Academicstaff'), ('NS', 'Non-Academicstaff'), ('Nil', 'NIL')], default='Nil', max_length=3)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['-updated_at'], name='staffs_staf_updated_500466_idx')],
            },
        ),
    ]
